### ISSUE TITLE
Pointcloud maps cannot be saved as PCD

### ISSUE THREAD

**Issue by Joosoo1** [vectr-ucla/direct_lidar_inertial_odometry#12]
Under the livox branch: when I run `rosservice call /robot/dlio_map/save_pcd 0.1 ~/pcd/campus2`, the following error occurs:
![Point cloud map cannot be saved](https://github.com/vectr-ucla/direct_lidar_inertial_odometry/assets/65029285/b4de5027-f48d-436e-9067-b11b9e294d05)

**Comment by kennyjchen** [comment]
Hi @Joosoo1 -- the second argument should be just the folder you want the PCD to be saved in, i.e.

```
rosservice call /robot/dlio_map/save_pcd 0.1 ~/pcd
```

which will save the PCD into `~/pcd/dlio_map.pcd`. You can then rename the file afterwards.
