### ISSUE TITLE
trival typos

### ISSUE THREAD

**Issue by narutojxl** [vectr-ucla/direct_lidar_inertial_odometry#14]
Hello author,
Thanks for sharing your excellent work!  I have some trival questions.
Q1:  After firstly process imu after `this->imu_calibrated = true;`, it seems  `this->prev_imu_stamp` is equal to  `imu->header.stamp.toSec()`,  not the default zero value ?
https://github.com/vectr-ucla/direct_lidar_inertial_odometry/blob/4217a4c083c2ec7e0b61d740cc777e290f7c546c/src/dlio/odom.cc#L952

Q2: ros odometry linear velocity is in some body frame, not in a world frame `this->state.v.lin.b`?
https://github.com/vectr-ucla/direct_lidar_inertial_odometry/blob/4217a4c083c2ec7e0b61d740cc777e290f7c546c/src/dlio/odom.cc#L331

**Comment by dxdydz3dt** [comment]
Can you help me in regarding how to save the pose.txt file with time I want to use in my thesis.
like: t   x y z roll pitch yaw w (quaternion)
Thanks
