### ISSUE TITLE
Point Cloud Visualizations

### ISSUE THREAD

**Issue by rafaelspring** [vectr-ucla/direct_lidar_inertial_odometry#2]
Just a quick question: which app/lib/package was used to create the point cloud visualizations? These look very nice.

**Comment by kennyjchen** [comment]
Hi @rafaelspring -- we just use [RViz](http://wiki.ros.org/rviz/DisplayTypes/PointCloud) with a large decay time and low alpha value on the motion-corrected point clouds.

**Comment by juliangaal** [comment]
I guess you're talking about the setting in [this file](https://github.com/vectr-ucla/direct_lidar_inertial_odometry/blob/master/launch/dlio.rviz)?

**Comment by rafaelspring** [comment]
@kennyjchen thanks for the pointer! Are you using a particularly high resolution to render these or does RViz already give you the nice transparency effects using a low alpha value?

**Comment by kennyjchen** [comment]
It's a combination of RViz + a low alpha value and also using the full, motion-corrected point cloud during rendering.
