### ISSUE TITLE
Missing save_traj service

### ISSUE THREAD

**Issue by kthatav63** [vectr-ucla/direct_lidar_inertial_odometry#22]
Hey @kennyjchen,

Thank you for your work on DLIO, which I have recently tested and found to be highly effective. However, I've noticed that DLIO lacks the "**save_traj**" service available in DLO. This functionality is essential for my current project. Could you please let me know why it's missing in DLIO and how I can add it to the platform? Your help is greatly appreciated.

**Comment by kennyjchen** [comment]
Hi @kthatav63 -- yeah apologies, that service was added by request and we never transferred it over to DLIO. It should be straightforward to add though if you just look at the [PR](https://github.com/vectr-ucla/direct_lidar_odometry/pull/32).

**Comment by kthatav63** [comment]
Thank you!
