### ISSUE TITLE
Extrinsics and Ouster Driver

### ISSUE THREAD

**Issue by juliangaal** [vectr-ucla/direct_lidar_inertial_odometry#3]
Hi, and thanks for open sourcing your work!

I assume [your extrinsics](https://github.com/vectr-ucla/direct_lidar_inertial_odometry/blob/613a2f10accc9770bb67024be52ca3b3c5f47dbb/cfg/dlio.yaml#L34) are tailored to the OS1-64 and taking from the datasheet/driver, correct? Does `base_link`, your robot frame, refer to the `sensor frame` of the ouster driver [p. 14p](https://data.ouster.io/downloads/software-user-manual/software-user-manual-v2p0.pdf#e)?

**Comment by kennyjchen** [comment]
Hi @juliangaal -- thanks for the clarifying question. Yes, the current extrinsics assumes everything is with respect to the `os_sensor` frame, which we call `base_link` in the config file, and the IMU is transformed to be in `os_sensor` according to the document you posted above. And taking a look at [this thread](https://github.com/ouster-lidar/ouster-ros/issues/33), it seems that it has been confirmed that all points are relative to `os_sensor` (at least for the latest Ouster driver).

Ideally, if your Ouster is mounted onto some platform, `base_link` should be coincident with your platform's CG (center of gravity), and all LiDAR / IMU measurements should be relative to that CG. This is to account for the effects of [offsetting an accelerometer](https://github.com/TixiaoShan/LIO-SAM/issues/204). In practice though, depending on how big or small your robot / platform is and how far away the Ouster is mounted from the CG, it's not too big of a deal to have everything relative to `os_sensor`.

Let me know if you have any other questions.

**Comment by juliangaal** [comment]
Got it.

Do you have any recommendations for external IMU calibration? Internal calibration is a little easier to find, to my knowledge, e.g. [allan variance](https://github.com/ori-drs/allan_variance_ros) and kalibr.

**Comment by kennyjchen** [comment]
Perhaps try the following:
- https://github.com/APRIL-ZJU/lidar_IMU_calib
- https://github.com/unmannedlab/imu_lidar_calibration
