### ISSUE TITLE
Pausing and resuming a rosbag cause the odometry to drift away

### ISSUE THREAD

**Issue by VRichardJP** [vectr-ucla/direct_lidar_inertial_odometry#47]
If you play a rosbag, pause it for a few seconds, then resume it, the robot pose will suddenly jump away, as if the robot had been moving during the pause.

Or at least it is the case with the feature/ros2 branch.

**Comment by VRichardJP** [comment]
Most likely a misconfiguration on my side.

**Comment by greymfm** [comment]
Please re-open issue -  I can confirm this (ROS1, MID-360) when temporary (3 secs) completely covering the LiDAR. The system cannot recover from this and 'oscillates away' (with odometry velocities >1m/sec) . I would like to add a filter to not allow such motions and to restart the computation states after detecting such high velocities...

**Comment by lacie-life** [comment]
@greymfm did you fix the problem? i also had a big drift when the robot jerked a bit, dlio couldn't recover
