### ISSUE TITLE
The rosbag used for testing seems to be invalid. 

### ISSUE THREAD

**Issue by xxkklose** [vectr-ucla/direct_lidar_inertial_odometry#51]
Would you please update the download link？Thanks a lot!
![ae79485d-df5a-41ae-8595-7afc0d3b9e97](https://github.com/vectr-ucla/direct_lidar_inertial_odometry/assets/61584491/a9e138ba-ad41-469c-a3c2-6aa5522a5f79)

**Comment by kennyjchen** [comment]
Apologies -- seems that the links broke after changes from UCLA's Google Drive. I reuploaded and fixed the links in the readme. Let me know if they work or not.

**Comment by xxkklose** [comment]
@kennyjchen Perfect. Both links work. Thanks for your work.
