### ISSUE TITLE
keyframe-based loop closure in paper

### ISSUE THREAD

**Issue by michael-sz** [vectr-ucla/direct_lidar_inertial_odometry#7]
great job! thanks for sharing!

1. when i read the paper, i found the part of loop closure, but not found during the code .  will it be released in future? 
2.  if add gps positon as prior factor,  the way of lio-sam based on gtsam will be better?

**Comment by michael-sz** [comment]
got it, thanks for reply.
And if as you convenience , please show  me  the main distinction between dlio and dilom ,thanks.

**Comment by kennyjchen** [comment]
tl;dr -- 

- DLIO: LIO with fast and accurate motion correction
- DLIOM: SLAM with innovations in keyframing (resistances to slippage), submapping (looks at overlap / Jaccard index), and mapping (connectivity between keyframes) to increase overall reliability
