### ISSUE TITLE
Use for localization for already built map

### ISSUE THREAD

**Issue by iandresolares** [vectr-ucla/direct_lidar_inertial_odometry#80]
Hello,
First of all, thank you for your great contribution. Is it possible to use this package for localization once the map has been generated?

Thanks!

**Comment by kennyjchen** [comment]
Hi @iandresolares -- yes, it is possible. You basically just need to read in the PCD and set it as the first (and only) keyframe. Then, whenever you localize on the map, you will need to set the initial position.

**Comment by iandresolares** [comment]
Got it, will give it a try, thanks!

**Comment by Youngmh1** [comment]
> Got it, will give it a try, thanks!

Hello, I’m also trying to modify the relocation feature, but I’ve encountered some issues. Could you share your ideas on how to approach the modifications? Thank you!

**Comment by jomib** [comment]
Hi @iandresolares , were you able to get something like this to work? Or perhaps recommendations on how to use the generate PCD file from DLIO?
