### ISSUE TITLE
Ground Truth

### ISSUE THREAD

**Issue by dxdydz3dt** [vectr-ucla/direct_lidar_inertial_odometry#9]
Hello Guys!
Where to get the ground truth of your provided datasets?

**Comment by kennyjchen** [comment]
Hi @dxdydz3dt (great name) -- unfortunately we do not have any ground truth for the provided test datasets.

**Comment by dxdydz3dt** [comment]
Hi..
Thanks :)
Is it possible to arrange it because I need it for my thesis?
Thanks

**Comment by kennyjchen** [comment]
Perhaps in the future for newer datasets, but not for the ones currently provided. We recommend using public benchmark datasets. Sorry, and thanks for the interest!
